config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

# pybo 뒤에 /를 붙여줌으로서 localhost:8000/pybo를 자동으로 pybo/로 변환해줌
# pybo --> homedirectory 느낌
urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), # pybo/ 요청을 받으면 pybo/urls.py 를 읽어 처리 하라는 뜻.
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'), # '/'에 해당하는 path
]

pybo/urls.py
from django.urls import path

from . import views
from .views import base_views, answer_views, question_views

# 서로 다른 앱 동일한 별칭 사용시 중복을 방지하기 위함.
app_name = 'pybo'

# 명확하게 볼 수 있게 변경
# path(웹주소, 실행 메소드, url_name)
urlpatterns = [
    # base_views
    path('', base_views.index, name='index'), # path에 'pybo/'가 생략된 것.
    path('<int:question_id>/', base_views.detail, name='detail'), # 질문 링크를 타면 들어가는 링크.
    # question_views
    path('question/create/', question_views.question_create, name='question_create'), #질문 등록
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'), # 질문 변경
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'), # 질문 삭제
    # answer_views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),  # 답변 등록
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'), # 답변 변경
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'), # 답변 삭제
    path('answer/vote/<int:question_id>/', question_views.question_vote, name = 'question_vote'), # 추천인 등록
]

# name : 수정될 수 있는 url 하드코딩을 별칭을 부여.

pybo/models.py
# Create your models here.
from djongo import models
from django.contrib.auth.models import User # 사용자 모델, 회원 가입시 데이터 저장에 사용했던 모델.


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)# 제한된 글자시 CharFiled 사용
    content = models.TextField()# 글자 제한 없을 시 TextFiled() 사용.
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()
    voter = models.ManyToManyField(User, related_name='voter_question') # 추천인 추가, User를 둘다 사용함으로 User모델로 접근할 때 author 기준인지 voter 기준인지 모호해짐 -->related_name 인수 추가
    # ManyToMany 함수가 같은 사용자가 같은 게시물에 많은 추천을 누를 시 오류도 발생하지 않고, 추가도 되지않게 한다.
    def __str__(self): # Question.objects.all() 에서 제목으로 볼 수 있게해줌.
        return self.subject


class Answer(models.Model):
    # 무조건 있어야 함으로 강제로 임의값을 주입.
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    #질문에 대한 답변이므로 ForeignKey를 통해 질문과 연결.
    question = models.ForeignKey(Question, on_delete=models.CASCADE) # CASCADE를 통해 질문 삭제시 응답도 삭제.
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name = 'voter_answer')

pybo/forms.py
''' 페이지 요청시 전달되는 피라미터들을 쉽게 관리하기위한 클래스,
필수 파라미터의 값이 누락되지 않았는지, 파라미터의 형식은 적절한지 등을 검증할 목적으로 사용,
HTML을 자동으로 생성하거나 폼에 연결된 모델을 이용하여 데이터를 저장하는 기능'''

from django import forms
from pybo.models import Question, Answer

# form.ModelForm, form.Form 존재
# forms.ModelForm : 모델 폼은 모델(Model)과 연결된 폼으로 폼을 저장하면 연결된 모델의 데이터를 저장할수 있는 폼
class QuestionForm(forms.ModelForm):
    class Meta: # Meta 클래스 반드시 필요/ 사용할 모델, 모델의 속성을 명시.
        model = Question # 사용할 모델
        fields = ['subject', 'content'] # QuestionForm에서 사용할 모델의 속성
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'subject': '제목',
            'content': '내용',
        }
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

pybo/views/answer_views.py
from django.contrib.auth.decorators import login_required
from django.core.checks import messages
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from django.utils import timezone

from pybo.forms import AnswerForm
from pybo.models import Answer, Question


@login_required(login_url='common:login') # 로그인이 필요한 함수를 의미., 로그아웃시 자동으로 로그인 페이지로 이동.
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk= question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=question.id), answer.id
            ))# 앵커를 포함, resolbe_url => 실제로 호출되는 URL 문자열을 리턴하는 장고함수.
    else:
        # 답변등록 URL인 /answer/create가 GET 방식으로 호출 --> HttpResponseNotAllowed의 405 오류 발생 --> 따라서 그냥 AnswerForm으로 이동하게 수정.
        form = AnswerForm()
    context = {'question':question, 'form':form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error('수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method ==  "POST" :
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
              resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else :
        form = AnswerForm(instance=answer)
    context = {'answer':answer, 'form':form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error('삭제권한이 없습니다')
    else :
        answer.delete()
    return redirect('{}#answer_{}'.format(
        resolve_url('pybo:detail', question_id = answer.question.id), answer.id))

pybo/views/base_views.py
# 기본관리
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from ..models import Question


# 질문 목록 화면
def index(request):
    page= request.GET.get('page',1) # 페이지, GET으로 호출 됐을경우, page 디폴트 값이 1 을 의미
    kw= request.GET.get('kw', '') # 검색어
    # 질문 목록 출력.
    question_list = Question.objects.order_by('-create_date') # order_by -> 조회 결과를 정렬, '-' 유 : 역방향 정렬/무 : 순방향 정렬
    if kw:
        question_list =question_list.filter(
            Q(subject__icontains=kw) | # 제목 검색, 제목에 kw이 포함되었는지 / contains는 대소문자를 가려서 찾는데 icontains는 가리지 않음.
            Q(content__icontains=kw) | # 내용 검색
            Q(answer__content__icontains=kw)| # 답변 내용 검색
            Q(author__username__icontains=kw)| # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw) # 답변 글쓴이 검색, '__'를 이용해 하위 속성 접근 가능.
        ).distinct() # 검색 결과 중복 방지
    paginator =  Paginator(question_list, 10) # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page) # 요청된 페이지에 해당된 객체
    context = {'question_list': page_obj,'page':page,'kw':kw}
    # render 는 pyhon 데이터를 템플릿에 적용해 HTML로 반환. 'pybo/question_list.html' --> 템플릿 : HTML과 유사하지만 파이썬 데이터를 읽을 수 있는 파일.
    return render(request, 'pybo/question_list.html', context)

# 질문 선택시 화면
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id) #pk : Question 모델의 기본키
    context = {'question':question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/question_views.py
# 질문 관리
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone

from pybo.forms import QuestionForm
from pybo.models import Question


@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST': # POST시 실행
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False) # commit=False => 임시저장
            question.author = request.user # author 속성에 로그인 계정 저장.
            question.create_date=timezone.now()
            question.save()
            return redirect('pybo:index')
    else: # GET일떄 실행
        form = QuestionForm
    context = {'form': form}
    return render(request,'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request,'수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST" :
        form = QuestionForm(request.POST, instance=question) # instance 기준으로 수정해 POST로 덮어 씌움.
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date=timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else :
        form = QuestionForm(instance=question) # 폼의 속성이 instance 값으로 채워짐
    context={'form':form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

@login_required(login_url='coommon:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error('본인이 작성한 글에는 추천할수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 --> <!-- 수정권환이 없을 경우 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                </a>
                {% if request.user == question.author %} <!-- 사용자와 글쓴이가 동일한 경우 버튼이 보임 -->
                <a href="{% url 'pybo:question_modify' question.id  %}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <!-- javascript:void(0) = 해당 링크 클릭해도 아무런 동작을 하지 않음-->
                <!-- data-uri 속성은 스크립트에서 클릭 이벤트 발생시 this.dataset.uri와 같이 사용하여 그 값을 얻을 수 있다. -->
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" >{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2"> {{ answer.author.username }} </div>
                    <div> {{ answer.create_date }} </div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == answer.author %}
                <a href="{% url 'pybo:answer_modify' answer.id  %}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea> <!-- 로그인 전에는 텍스트를 못침. -->
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

{# csrf_token : 폼에서 전송한 데이터가 실제 웹페이지에서 전송한 데이터인지 확인(보안과 관련), 폼 바로 밑에 위치. #}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post"> {# 해당 method를 action의 URL에 전달, action 속성을 지정하지 않으면 현재 페이지의 URL이 디폴트 action으로 설정 #}
        {% csrf_token %}
        {# question_create 함수에서 전달한 QeustionForm의 객체, 폼에 정의한 subject, content속성에 해당하는 HTML코드를 자동생성, 동일한 템플릿을 여러 곳에서 사용할 경우 action을 비워둠.#}
        {# {{ form.as_p }} 디자인 측면에서 별로 #}
         <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
           <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td> <!-- 글쓴이 추가 -->
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
           href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
           <a class="page-link" data-page="{{ question_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}