common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

# pybo 뒤에 /를 붙여줌으로서 localhost:8000/pybo를 자동으로 pybo/로 변환해줌
# pybo --> homedirectory 느낌
urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), # pybo/ 요청을 받으면 pybo/urls.py 를 읽어 처리 하라는 뜻.
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'), # '/'에 해당하는 path
]

pybo/urls.py
from django.urls import path

from . import views
from .views import base_views, answer_views, question_views

# 서로 다른 앱 동일한 별칭 사용시 중복을 방지하기 위함.
app_name = 'pybo'

# 명확하게 볼 수 있게 변경
# path(웹주소, 실행 메소드, url_name)
urlpatterns = [
    # base_views
    path('', base_views.index, name='index'), # path에 'pybo/'가 생략된 것.
    path('<int:question_id>/', base_views.detail, name='detail'), # 질문 링크를 타면 들어가는 링크.
    # question_views
    path('question/create/', question_views.question_create, name='question_create'), #질문 등록
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'), # 질문 변경
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'), # 질문 삭제
    # answer_views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),  # 답변 등록
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'), # 답변 변경
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'), # 답변 삭제
    path('answer/vote/<int:question_id>/', question_views.question_vote, name = 'question_vote'), # 추천인 등록
]

# name : 수정될 수 있는 url 하드코딩을 별칭을 부여.

pybo/views/base_views.py
# 기본관리
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from ..models import Question


# 질문 목록 화면
def index(request):
    page= request.GET.get('page',1) # 페이지, GET으로 호출 됐을경우, page 디폴트 값이 1 을 의미
    kw= request.GET.get('kw', '') # 검색어
    # 질문 목록 출력.
    question_list = Question.objects.order_by('-create_date') # order_by -> 조회 결과를 정렬, '-' 유 : 역방향 정렬/무 : 순방향 정렬
    if kw:
        question_list =question_list.filter(
            Q(subject__icontains=kw) | # 제목 검색, 제목에 kw이 포함되었는지 / contains는 대소문자를 가려서 찾는데 icontains는 가리지 않음.
            Q(content__icontains=kw) | # 내용 검색
            Q(answer__content__icontains=kw)| # 답변 내용 검색
            Q(author__username__icontains=kw)| # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw) # 답변 글쓴이 검색, '__'를 이용해 하위 속성 접근 가능.
        ).distinct() # 검색 결과 중복 방지
    paginator =  Paginator(question_list, 10) # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page) # 요청된 페이지에 해당된 객체
    context = {'question_list': page_obj,'page':page,'kw':kw}
    # render 는 pyhon 데이터를 템플릿에 적용해 HTML로 반환. 'pybo/question_list.html' --> 템플릿 : HTML과 유사하지만 파이썬 데이터를 읽을 수 있는 파일.
    return render(request, 'pybo/question_list.html', context)

# 질문 선택시 화면
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id) #pk : Question 모델의 기본키
    context = {'question':question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{# HTML 표준 #}
{# 상속을 통해 표준을 만들어준다 #}
{# 스태틱 파일 사용하기 위해 load static 삽입 #}
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트는 /body 위에 표시하는것이 바람직함, 값을 읽어오지 못하는 문제, 화면 로딩 지연 문제 발생을 예방 -->
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 오류 발생시 어떤 오류가 발생한지 알려줌 -->
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}<!-- 필드 오류 -->
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}<!-- 넌필드 오류 : 필드값과 상관없이 발생하는 오류 -->
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- include : 특정 위치에 다른 템플릿 삽입 가능. 중복을 제거하기 위함. -->
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %} <!-- 현재 사용자가 인증 되었는지 여부 -->
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>